services:
  database:
    image: localhost/postgres-age:latest
    build:
      context: ..
      dockerfile: ./docker/database/Dockerfile
    volumes:
      - db-volume:/var/lib/postgresql/18/docker
    security_opt:
      - seccomp:unconfined
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - "40002:5432"
    networks:
      - app-network
  llmserver:
    image: localhost/lawrag-llmserver:latest
    build:
      context: ..
      dockerfile: ./docker/llmserver/Dockerfile
    volumes:
      - llmserver-volume:/app/data
    security_opt:
      - seccomp:unconfined
    environment:
      LLM_HOST: "0.0.0.0"
      LLM_PORT: 8080
    ports:
      - "40003:8080"
    networks:
      - app-network
  web:
    image: localhost/lawrag:latest
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      database:
        condition: service_started
    volumes:
      - web-volume:/app/data
    security_opt:
      - seccomp:unconfined
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: database
      LLM_HOST: llmserver
      LLM_PORT: 8080
      FASTAPI_HOST: "0.0.0.0"
      FASTAPI_PORT: 8080
      RELEASE_MODE: 1
    ports:
      - "40001:8080"
    networks:
      - app-network
volumes:
  db-volume:
    driver: local
  llmserver-volume:
    driver: local
  web-volume:
    driver: local
networks:
  app-network:
    driver: bridge
